# Generated by Django 4.2.5 on 2023-09-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.CharField(max_length=100)),
                ('duree', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('prix_par_metre_carre', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='QuantiteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='high_level.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actions', models.ManyToManyField(to='high_level.action')),
            ],
        ),
        migrations.CreateModel(
            name='Usine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.departement')),
                ('machines', models.ManyToManyField(to='high_level.machine')),
                ('recette_biere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.recette')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.quantiteingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.departement')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='ingredients',
            field=models.ManyToManyField(to='high_level.ingredient'),
        ),
        migrations.AddField(
            model_name='action',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_level.machine'),
        ),
    ]
